name: julia
#version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
version: git
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: classic

apps:
  julia:
    command: bin/julia

parts:
  julia:
    plugin: dump
    prepare: |
      #wget https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6.2-linux-x86_64.tar.gz
      #tar -xf julia-0.6.2-linux-x86_64.tar.gz
      tar -xf /home/mortenpi/Julia/julia-0.6.2-linux-x86_64.tar.gz
      cp -R julia-d386e40c17/* $SNAPCRAFT_PART_INSTALL/
